### ISSUE TITLE
No TAP devices detected on JTAG chain 0

### ISSUE THREAD

**Issue by Iamdeanwong** [Intel-BMC/asd#51]
Hi, ALL:  
I have a question for ASD 1.5.1,  
the platform is bhs, 
checked the host power was ON,  
then run ``dflaunch startCscripts.py -a ipc`` on window 10,  

I saw the below info,   
should I need to set what something?  

````
Info - Added debug port 0 for probe ASD_JTAGProbe

Warning - No TAP devices detected on JTAG chain 0
WARNING!  Failed to determine CPU device type!

Warning - No TAP devices detected on JTAG chain 1


CScripts failed to start due to the following error:
Failed to get the Core or Uncore name!


You may attempt to reinitialize CScripts with the "init_cscripts()" function.
>>>
````

On the BMC console shown below   
````
target_get_fds, null or uninitialized state
line BMC_PWRGD3 doesn't exist
````

**Comment by asdbuild** [comment]
Hi, can you open an Intel IPS issue on this and file it against  tool.at_scale_debug,  we will be able to better help you through that route, thanks,

**Comment by Iamdeanwong** [comment]
OK, thanks~
